/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Recipe API
 * OpenAPI spec version: 1.0.0
 */

export interface Recipe {
  id: number;
  title: string;
  description: string;
  userId: number;
}
