/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Recipe API
 * OpenAPI spec version: 1.0.0
 */

export interface RecipeIngredient {
  id: number;
  name: string;
  amount: string;
  recipeId: number;
}
